### ISSUE TITLE
2024 RoboCup@Home记得更新在README啊啊啊

### ISSUE THREAD

**Issue by 0nhc** [mvyp/.github#1]
@HARROLDX @ACC47max

**Comment by 0nhc** [comment]
@linden713 什么情况怎么没人理我啊啊啊啊

**Comment by HARROLDX** [comment]
🤩🤩🤩🤩🤩🤩🤩



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhengxiao Han ***@***.***&gt;
发送时间: 2024年6月28日 08:25
抄送: 夏佳炜 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [mvyp/.github] 2024 ***@***.***记得更新在README啊啊啊 (Issue #1)





 
@linden713 什么情况怎么没人理我啊啊啊啊

**Comment by linden713** [comment]
Closed as completed
